# Uncomment the next line to define a global platform for your project

use_frameworks!

platform :ios, '8.0'

target 'KKGame' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for KKGame

  pod 'KKDuktape', '~> 1.0.1'

end
